skeleton/src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CategoryP", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categoryP;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategory(): ?CategoryP
    {
        return $this->categoryP;
    }

    public function setCategory(?CategoryP $categoryP): self
    {
        $this->categoryP = $categoryP;

        return $this;
    }


    public function getCategoryP(): ?CategoryP
    {
        return $this->categoryP;
    }

    public function setCategoryP(?CategoryP $categoryP): self
    {
        $this->categoryP = $categoryP;

        return $this;
    }
}

skeleton/templates/site/create.html.twig
{% extends 'base.html.twig' %}

{% form_theme formArticle 'bootstrap_4_layout.html.twig' %}

{% block body %}

    <h1>création d'un article</h1>

    {{ form_start(formArticle) }}

    {{ form_row(formArticle.title, {'attr' : {'placeholder' : "titre de l'article"}} ) }}
    {{ form_row(formArticle.category) }}
    {{ form_row(formArticle.content, {'attr' : {'placeholder' : "Contenu de l'article"}} ) }}
    {{ form_row(formArticle.image, {'attr' : {'placeholder' : " URL de l'image"}} ) }}

    <button type="submit" class="btn btn-primary" >

        {% if editMode %}
        enregistrer les modifications
        {% else %}
        ajouter l'article
        {% endif %}

    </button>

    {{ form_end(formArticle) }}


{% endblock %}

skeleton/templates/site/createProduit.html.twig
{% extends 'base.html.twig' %}

{% form_theme formProduit 'bootstrap_4_layout.html.twig' %}

{% block body %}

    <h1>création d'un produit</h1>

    {{ form_start(formProduit) }}

    {{ form_row(formProduit.title, {'attr' : {'placeholder' : "titre de l'article"}} ) }}
    {{ form_row(formProduit.category) }}
    {{ form_row(formProduit.content, {'attr' : {'placeholder' : "Contenu de l'article"}} ) }}
    {{ form_row(formProduit.image, {'attr' : {'placeholder' : " URL de l'image"}} ) }}

    <button type="submit" class="btn btn-primary" >

        {% if editMode %}
            enregistrer les modifications
        {% else %}
            ajouter le produit
        {% endif %}

    </button>

    {{ form_end(formProduit) }}


{% endblock %}

skeleton/templates/site/home.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="container text-center">
        <h1>Bienvenue !</h1>
    </div>



    <div id="carrousel">
        <ul>
            <li><img src="http://lorempixel.com/700/200/" /></li>
            <li><img src="http://lorempixel.com/g/700/200/" /></li>
            <li><img src="http://lorempixel.com/700/200/abstract/" /></li>
        </ul>
    </div>


    <p></p>

    <h2>Une Marque Française</h2>

    <p>CROISIAUX ANAIS est une jeune marque française en prêt-à-porter féminin moyen et haut de gamme déposée en avril 2016 en pleine expansion.</p>

    <p>Sa production est entièrement belge.</p>

    <p>Des tissus uniques imprimés et fabriqués en Belgique.</p>

    <p>La marque est distribuée via sa boutique en ligne, plateformes internationales de vente en B2B et B2C, des showrooms et des boutiques.<p>

    <p> CROISIAUX ANAIS vous propose ses collections  uniques ou déclinées en plusieurs tailles en prêt-à-porter ou sur-mesure, en fonction des saisons tout en s’inspirant des tendances actuelles.</p>

    <h2>SON PORTRAIT</h2>

    <p>

        Née à Mons, en 1993 de nationalité belge, Anais Croisiaux obtient à la fin de ses études techniques secondaires à l'Athénée Royal de PERUWELZ (Belgique) son diplôme de couturière. Elle veut poursuivre ses études et devenir styliste.



        C'est un rêve qui deviendra réalité en juin 2016: Diplômée de la Haute Ecole Francisco Ferrer à BRUXELLES en Arts Appliqués section stylisme modélisme.  Une des meilleures écoles de mode de Belgique très réputée dans le milieu de la mode.

        Durant ses études, elle effectue un stage de quatre mois chez la très réputée Styliste Liégeoise, Ann PIRON, spécialisée dans la création de robes de mariée et de cérémonie.



        Cette collaboration lui a permis de découvrir et d'apprendre de nouvelles techniques telles que travailler la dentelle et les finitions Haut de gamme.

        Dès sa sortie de l'école, elle décide de déposer sans attendre sa marque de vêtements et accessoires qui porte tout simplement ses nom et prénom.



        Chacune de ses créations est unique.



        Elle dessine, crée, produit et laisse libre cours à sa créativité.</p>

    <div id="social-platforms">
        <h1>Retrouve moi sur les réseaux sociaux !</h1>

        <a class="btn btn-icon btn-facebook" href="https://www.facebook.com"><i class="fa fa-facebook"></i><span>Facebook</span></a>
        <a class="btn btn-icon btn-twitter" href="https://twitter.com"><i class="fa fa-twitter"></i><span>Twitter</span></a>
        <a class="btn btn-icon btn-googleplus" href="https://www.google.com"><i class="fa fa-google-plus"></i><span>Google+</span></a>
        <a class="btn btn-icon btn-pinterest" href="https://www.pinterest.fr/"><i class="fa fa-pinterest"></i><span>Pinterest</span></a>
    </div>



{% endblock %}

skeleton/templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block body %}
    <section class="articles">

        {% for article in articles %}
            <article>
                <h2>{{ article.title }} </h2>

                {% if is_granted('ROLE_ADMIN') %}
                <a href="#" class="btn btn-danger delete-article" data-id="{{ article.id }}">Supprimer</a>
                {% endif %}

                <div class="metadata">écrit le {{ article.createdAt | date('d/m/Y') }} a {{ article.createdAt | date('H:i') }}dans la catégorie {{ article.category.title }}</div>

                <div class="content">

                    <img src= "{{ article.image }}" alt="">

                </div>

                <div class="content">
                {{ article.content | raw }}
                <a href="{{ path('blog_show', { 'id' : article.id }) }}" class="btn btn-primary">lire la suite</a>
                </div>

            </article>

        {% endfor %}

    </section>

{% endblock %}

{% block javascripts %}
    <script src="\skeleton\public\js\delete.js"></script>
{% endblock %}

skeleton/templates/site/produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits{% endblock %}

{% block body %}
    <section class="produits">

        {% for produit in produits %}
            <article>
                <h2>{{ produit.title }} </h2>

                <div class="metadata">écrit le {{ produit.createdAt | date('d/m/Y') }} a {{ produit.createdAt | date('H:i') }} dans la catégorie {{ produit.category.title }}</div>

                <div class="content">

                    <img src= "{{ produit.image }}" alt="">

                </div>

                <div class="content">
                    {{ produit.content | raw }}
                    <a href="{{ path('produits_show', { 'id' : produit.id }) }}" class="btn btn-primary">lire la suite</a>
                </div>

            </article>

        {% endfor %}

    </section>

{% endblock %}

skeleton/templates/site/show.html.twig
{% extends ('base.html.twig') %}

{% block body %}

    <article>
        <h2>{{ article.title }}</h2>

        <div class="metadata">écrit le {{ article.createdAt | date('d/m/Y') }} a {{ article.createdAt | date('H:i')}} dans la catégorie {{ article.category.title }}</div>

        <div class="content">

            <img src=" {{ article.image }}" alt="">

        </div>

        <div class="content">
            {{ article.content | raw }}
        </div>

    </article>

    <section id="commentaires">
        <h1>{{ article.comments | length }} Commentaires :</h1>
        {% for comment in article.comments %}
        <div class="comment">
            <div class="row">
                <div class="col-3">
                    {{ comment.author }} (<small>{{ comment.createdAt | date ('d/m/Y a H:i') }}</small>
                </div>
                <div class="col">
                    {{ comment.content | raw}}
                </div>
            </div>
        </div>
        {% endfor %}

        {% if app.user %}
        {{ form_start(commentForm) }}
        {{ form_row(commentForm.author, {'attr' : {'placeholder': "Votre nom"}}) }}
        {{ form_row(commentForm.content, {'attr' : {'placeholder': "Votre commentaire"}}) }}



        <button type="submit" class="btn btn-primary">Commenter !</button>
        {{ form_end(commentForm) }}

        {% else %}
            <h2>vous ne pouvez pas commenter si vous n'étes pas connecter</h2>
            <a href="{{ path('security_login') }}" class="btn btn-primary">Connexion</a>

        {% endif %}


    </section>

{% endblock %}

skeleton/templates/site/show2.html.twig
{% extends ('base.html.twig') %}

{% block body %}

    <article>
        <h2>{{ produit.title }}</h2>

        <div class="metadata">écrit le {{ produit.createdAt | date('d/m/Y') }} a {{ produit.createdAt | date('H:i')}} dans la catégorie {{ produit.category.title }}</div>

        <div class="content">

            <img src=" {{ produit.image }}" alt="">

        </div>

        <div class="content">

            {{ produit.content | raw }}
            <p>Pour plus d'information sur le produit vous pouvez passer par la boutique grace a ce lien <a href="https://www.croisiauxanais.com/">Boutique</a> </p>

        </div>

    </article>


{% endblock %}